// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2BLNvT_MncrfTQfyOvDco6G6ovkjh7L4',
    appId: '1:70534019948:web:e170387b34d588d0e79149',
    messagingSenderId: '70534019948',
    projectId: 'example-9b495',
    authDomain: 'example-9b495.firebaseapp.com',
    storageBucket: 'example-9b495.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwafWgYncTKNLA91jS8ukJ-kIngxPaj2U',
    appId: '1:70534019948:android:39728feeec3e8bf6e79149',
    messagingSenderId: '70534019948',
    projectId: 'example-9b495',
    storageBucket: 'example-9b495.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATg_UOsxCffnAlqbs_XsQIZBXcgeAernI',
    appId: '1:70534019948:ios:42037c82b0b20083e79149',
    messagingSenderId: '70534019948',
    projectId: 'example-9b495',
    storageBucket: 'example-9b495.appspot.com',
    iosClientId: '70534019948-fk6gmpa2ddu97k47vtmbquds9g03spf5.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseLoginExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATg_UOsxCffnAlqbs_XsQIZBXcgeAernI',
    appId: '1:70534019948:ios:42037c82b0b20083e79149',
    messagingSenderId: '70534019948',
    projectId: 'example-9b495',
    storageBucket: 'example-9b495.appspot.com',
    iosClientId: '70534019948-fk6gmpa2ddu97k47vtmbquds9g03spf5.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseLoginExample',
  );
}
